apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow-io
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "100"
  fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: jb-claim
 annotations:
   volume.beta.kubernetes.io/storage-class: "slow-io"
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 4Gi
